char_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import check_password_hash
from char_inventory.forms import UserLoginForm
from char_inventory.models import User,db,Character


#Imports
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth',__name__, template_folder='auth_templates')

@auth.route('/signup', methods= ['GET','POST'])
def signup():
    form =  UserLoginForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            print(email,password)

            user=User(email, password = password)
            
            db.session.add(user)
            db.session.commit()
            
            flash(f'You have successfuly created a user account {email}', 'User_created')
            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')

    return render_template('signup.html', form=form)

@auth.route('/signin', methods = ["GET", "POST"])
def signin():
    form =  UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data

            print(email,password)

            logged_user = User.query.filter(User.email== email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in', 'auth-success')
                return redirect(url_for('site.profile'))

            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect (url_for(auth.signin))
            
            

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))


@auth.route('/ownedCharacter',methods = ['GET'])
@login_required
def owned():
    owner = current_user.token
    characters = Character.query.filter_by(user_token = owner).all()
    return render_template('ownedCharacter.html',
            characters = characters,
            owner = owner )
            
    
    

char_inventory/site/routes.py
from typing import Collection
from flask import Blueprint, render_template, redirect, url_for, flash,json, request, jsonify
from flask_login.utils import login_required
from char_inventory.forms import submitData,UserLoginForm, commitChar
from char_inventory.models import  Character,db, User,character_schema, characters_schema
from char_inventory.helpers import token_required
from char_inventory import Config
from char_inventory.buildCharacter.browserCode import createCharacter, runCreate
from flask_login import login_user, logout_user, current_user, login_required
from char_inventory.buildCharacter.myData import classes, raceList, names, races
# from buildCharacter.randomCode import runCreate
# from buildCharacter.randomCode import createChar


'''
    Note that in the below code,
    some arguments are specified when creating the Blueprint object
    The first argument, 'site', is the Blueprint's name,
    which is used by Flask's routing mechanism.

    The Second argument, __name__, is the Blueprint's import name,
    which Flask uses to locate the Blueprint's resources.    
'''

site = Blueprint('site', __name__, template_folder ='site_templates')
@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@site.route('/creation', methods = ["GET", "POST"])
def creation():
    form =  submitData()
    formTwo = commitChar()
    name = None
    gender = None
    thisRace = None
    thisClass = None
    if form.validate_on_submit():
        print(form.gender.data)
        theRandom = createCharacter(form.name.data.lower(), form.gender.data.lower(), form.thisRace.data.lower(), form.thisClass.data.lower(), int(form.level.data))
        runCreate(theRandom)
        gender = form.gender.data 
        form.gender.data = ''
        level = form.level.data
        form.level.data = ''
        name = form.name.data
        form.name.data = ''
        thisRace = form.thisRace.data
        form.thisRace.data = ''
        thisClass = form.thisClass.data
        form.thisClass.data = ''
        commitCharacter=Character(theRandom.name.title(), theRandom.level, theRandom.race, theRandom._class, theRandom.hp, theRandom.ac, theRandom.stats['str'],
        theRandom.stats['dex'],theRandom.stats['con'],theRandom.stats['int'],theRandom.stats['wis'],
        theRandom.stats['cha'], theRandom.dc, current_user.token)
        
        
    
        # if formTwo.validate_on_submit():
        #     print('test')
            # answer = formTwo.answer.data 
            # if answer == 'Yes':
        db.session.add(commitCharacter)
        db.session.commit()        
                # formTwo.answer.data  = ''    
                   
                
        
        flash(f'Congrats! {theRandom.name.title()} The {theRandom.gender.title()}, {theRandom.race.title()}, {theRandom._class.title()} submitted successfully!')
        flash(f'Stat rolls: {theRandom.charStats} {theRandom.race.title()}  Racial Bonus: {races[theRandom.race]}')   
        return render_template('creation.html', 
            form= form,
            # formTwo = formTwo,
            gender = gender,
            level = level,
            name = name,
            thisClass = thisClass,
            thisRace = thisRace,
            theRandom = theRandom
            )
            
    else: 
        return  render_template('creation.html', 
            form= form,
            gender = gender,
            name = name,
            thisClass = thisClass,
            thisRace = thisRace,
            )
        

   
# @site.route('/displayCharacter',methods = ['GET'])
# @token_required
# def displayCharacter(current_user_token):
#     owner = current_user_token.token
#     characters = Character.query.filter_by(user_token = owner).all()
#     response = characters_schema.dump(characters)
#     return render_template('displayCharacter.html',
#             owner = owner,
#             characters = characters,
#             response = response)



@site.route('/availableCharacter',methods = ['GET'])
def availableCharacter():
    characters = Character.query.all()
    return render_template('availableCharacter.html',
            characters = characters )
    
    
            
            

            

char_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Character Generator</title>
</head>
<body>

    <!-- NavBar Here-->
    <nav class="ct-nav">
        <div><img src="../static/css/images/d20logo.jfif" alt="D20 Logo"></div>
        
        <!-- Nav Items -->
        <div>
            <ul id='horizontal-list'>
                <!-- <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a> -->
                <a href="{{ url_for('site.availableCharacter') }}">
                    <li>Generator Universe</li>
                </a>
               <!-- User Auth Check for Signin/SignUp Nav Buttons -->
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li> 
                </a>
                <a href="{{ url_for('site.creation') }}">
                    <li>Create</li>
                </a> 
                
                
                <a href="{{ url_for('auth.owned' )}}">
                    <li>My Characters</li>
                </a><a href="{{ url_for('auth.logout' )}}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- End of Nav -->

        {% block content %}
        {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>
                
                
               
                
                
                

    

char_inventory/templates/form.html
<!-- HTML Produced By the FlaskForm -->

<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password Here...") }}

        </fieldset>
    </div>
    <!-- Submit Button Area -->
    {{ form.submit_button(class = "btn btn-primary btn-block") }}
</form>